### ISSUE TITLE
scte35: create constants for all segmentation descriptor types

### ISSUE THREAD

**Issue by ollytom** [untangledco/streaming#3]
The values are documented in SCTE 35 section SCTE 35 section 10.3.3.1.
Right now we have magic values floating around. See in particular:

	crc_32.go:95: 	0x30476DC0,
	splice_descriptor.go:152: 		case 0x34, 0x30, 0x32, 0x36, 0x38, 0x3a, 0x44, 0x46:
	splice_descriptor.go:206: 		case 0x34, 0x30, 0x32, 0x36, 0x38, 0x3a, 0x44, 0x46:
	splice_info.go:17: 	SAPNone                     = 0x30

These should be constants named, for example, ProviderAdStart or so.

**Comment by sagnikc395** [comment]
Hi, for this splice_descriptor.go:152 , I created a pull request. I think I got it , but not I not sure.😅

For slice_info.go:17 , this seems to be already changes into a named constant.

<img width="477" alt="Screenshot 2024-05-16 at 11 16 14 PM" src="https://github.com/untangledco/streaming/assets/118270727/e16d2100-b5b9-4c5f-b3bf-5074c5ff11de">

**Comment by ollytom** [comment]
Remaining parts of our package using integer literals instead of named constant segmentation descriptor types are at:

	scte35_test.go:148: 					Type:     33,
	scte35_test.go:161: 					Type:     48,
